on:
  push:
    branches:
      - main

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - name: Config Clearing
      run: php artisan config:clear

    - name: Cache Clearing
      run: php artisan cache:clear

    - name: Generate Key
      run: php artisan key:generate

    - name: Run Dispatch Job
      run: php artisan queue:dispatch-movie-cache-job && php artisan queue:work && php aritsan schedule:work

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /htdocs/laravel-demo/